import { Notification } from '@/entities/Notification.entity';

export const mockNotifications: Notification[] = [
  {
    id: 1,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 0,
    userName: 'Sistema',
    userId: 0,
    message: 'Tienes 5 nuevas resoluciones pendientes de revisión.',
    timestamp: '2024-07-10T23:27:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 2,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 1234,
    userName: 'María López',
    userId: 201,
    message: 'La resolución #1234 ha sido creada y está lista para tu aprobación.',
    timestamp: '2024-07-10T23:28:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 3,
    type: 'cancel-cpc',
    entity: 'cpc',
    entityId: 0,
    userName: 'Sistema',
    userId: 0,
    message: 'Se han cancelado 2 CPC recientemente.',
    timestamp: '2024-07-10T23:29:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 4,
    type: 'new-any',
    entity: 'general_request',
    entityId: 0,
    userName: 'Sistema',
    userId: 0,
    message: 'Han llegado 3 nuevas solicitudes a tu bandeja de entrada.',
    timestamp: '2024-07-10T23:30:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 5,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 1235,
    userName: 'Pedro García',
    userId: 202,
    message: 'La resolución #1235 requiere tu firma digital.',
    timestamp: '2024-07-10T23:31:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 6,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 1230,
    userName: 'Ana Fernández',
    userId: 203,
    message: 'Se ha modificado la resolución #1230. Revisa los cambios.',
    timestamp: '2024-07-10T23:32:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 7,
    type: 'new-cpc',
    entity: 'cpc',
    entityId: 0,
    userName: 'Sistema',
    userId: 0,
    message: 'Has aprobado un nuevo CPC exitosamente.',
    timestamp: '2024-07-10T23:33:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 8,
    type: 'cancel-cpc',
    entity: 'cpc',
    entityId: 7890,
    userName: 'Juan Pérez',
    userId: 204,
    message: 'El CPC #7890 ha sido cancelado por falta de documentación.',
    timestamp: '2024-07-10T23:34:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 9,
    type: 'new-any',
    entity: 'user_request',
    entityId: 345,
    userName: 'Carlos Ruiz',
    userId: 205,
    message: 'Tienes una nueva solicitud de información del usuario #345.',
    timestamp: '2024-07-10T23:35:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 10,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 1236,
    userName: 'Sistema',
    userId: 0,
    message: 'Una nueva resolución ha sido asignada a tu equipo.',
    timestamp: '2024-07-10T23:36:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 11,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 1237,
    userName: 'Sistema',
    userId: 0,
    message: 'La resolución #1237 está a punto de vencer.',
    timestamp: '2024-07-10T23:37:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 12,
    type: 'new-cpc',
    entity: 'cpc',
    entityId: 7891,
    userName: 'Laura Giménez',
    userId: 206,
    message: 'El CPC #7891 ha sido aprobado y enviado para registro.',
    timestamp: '2024-07-10T23:38:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 13,
    type: 'cancel-cpc',
    entity: 'cpc',
    entityId: 7892,
    userName: 'Roberto Soto',
    userId: 207,
    message: 'El CPC #7892 fue rechazado por errores en el formulario.',
    timestamp: '2024-07-10T23:39:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 14,
    type: 'new-any',
    entity: 'support_message',
    entityId: 0,
    userName: 'Sistema',
    userId: 0,
    message: 'Tienes un nuevo mensaje en el centro de soporte.',
    timestamp: '2024-07-10T23:40:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 15,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 1238,
    userName: 'Silvia Díaz',
    userId: 208,
    message: 'La resolución #1238 ha sido archivada con éxito.',
    timestamp: '2024-07-10T23:41:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 16,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 1239,
    userName: 'Martín Castro',
    userId: 209,
    message: 'Necesitas revisar los comentarios en la resolución #1239.',
    timestamp: '2024-07-10T23:42:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 17,
    type: 'new-cpc',
    entity: 'cpc',
    entityId: 7893,
    userName: 'Elena Vargas',
    userId: 210,
    message: 'Se ha solicitado un nuevo CPC con el número #7893.',
    timestamp: '2024-07-10T23:43:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 18,
    type: 'cancel-cpc',
    entity: 'cpc',
    entityId: 7894,
    userName: 'Sistema',
    userId: 0,
    message: 'El proceso de cancelación del CPC #7894 ha iniciado.',
    timestamp: '2024-07-10T23:44:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 19,
    type: 'new-any',
    entity: 'case',
    entityId: 5678,
    userName: 'Sistema',
    userId: 0,
    message: 'Hay una actualización importante sobre tu caso #5678.',
    timestamp: '2024-07-10T23:45:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
  {
    id: 20,
    type: 'new-resolution',
    entity: 'resolution',
    entityId: 1240,
    userName: 'Sistema',
    userId: 0,
    message: 'Una nueva resolución crítica (#1240) requiere tu atención inmediata.',
    timestamp: '2024-07-10T23:46:45.000Z',
    viewed: false,
    viewedAt: '',
    viewedBy: 0,
  },
];
