import { sleep } from '../../utils';
import { Resolution } from './types';

const data: Resolution[] = [
  {
    id: 3027,
    number: 15,
    code: '03-027',
    name: 'BANDERA',
    alias: 'bandera',
    address: 'BANDERA 455',
    manager: 'SANCHEZ ALVAREZ CINTHIA ANDREA',
    email: null,
    phone: null,
  },
  {
    id: 3023,
    number: 14,
    code: '03-023',
    name: 'EYZAGUIRRE',
    alias: 'eyzaguirre',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3043,
    number: 16,
    code: '03-043',
    name: 'AV ARGENTINA',
    alias: 'av_argentina',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3045,
    number: 17,
    code: '03-045',
    name: 'SAN DIEGO',
    alias: 'san_diego',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3065,
    number: 23,
    code: '03-065',
    name: 'PEÑAFLOR',
    alias: 'peñaflor',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3006,
    number: 8,
    code: '03-006',
    name: 'ARLEGUI',
    alias: 'arlegui',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3104,
    number: 45,
    code: '03-104',
    name: 'LA PERLA',
    alias: 'la_perla',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3103,
    number: 44,
    code: '03-103',
    name: 'ALAMEDA',
    alias: 'alameda',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3099,
    number: 41,
    code: '03-099',
    name: 'PLAZA ITALIA',
    alias: 'plaza_italia',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3092,
    number: 34,
    code: '03-092',
    name: 'EL DOLAR',
    alias: 'el_dolar',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3089,
    number: 31,
    code: '03-089',
    name: 'LO PRADO',
    alias: 'lo_prado',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3066,
    number: 24,
    code: '03-066',
    name: 'CONCHA Y TORO',
    alias: 'concha_y_toro',
    address: 'AV CONCHA Y TORO 19',
    manager: 'JORQUERA MUÑOZ MARCO ANTONIO',
    email: null,
    phone: '224815212',
  },
  {
    id: 3140,
    number: 111,
    code: '03-140',
    name: 'PATRONATO',
    alias: 'patronato',
    address: 'DARDIGNAC 583',
    manager: 'NO DISPONIBLE',
    email: null,
    phone: '227321755',
  },
  {
    id: 3048,
    number: 19,
    code: '03-048',
    name: 'QUINTA REGION',
    alias: 'quinta_region',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3102,
    number: 43,
    code: '03-102',
    name: 'LIBERTAD',
    alias: 'libertad',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3101,
    number: 42,
    code: '03-101',
    name: 'ESCUELA MILITAR',
    alias: 'escuela_militar',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3095,
    number: 37,
    code: '03-095',
    name: 'CONDELL',
    alias: 'condell',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3098,
    number: 40,
    code: '03-098',
    name: 'EINSTEIN',
    alias: 'einstein',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3025,
    number: 18,
    code: '03-025',
    name: 'VIÑA DEL MAR',
    alias: 'vina_del_mar',
    address: 'AV VINA DEL MAR 105',
    manager: 'MARTINEZ PAREDES JUAN',
    email: null,
    phone: null,
  },
  {
    id: 3120,
    number: 50,
    code: '03-120',
    name: 'LIMA',
    alias: 'lima',
    address: null,
    manager: null,
    email: null,
    phone: null,
  },
  {
    id: 3145,
    number: 112,
    code: '03-145',
    name: 'TALCA',
    alias: 'talca',
    address: 'AV TALCA 455',
    manager: 'MARTINEZ ALVAREZ FABIOLA',
    email: null,
    phone: null,
  },
];

const client = async () => {
  await sleep(2000);
  return data;
};

export default client;
