import { formatCurrency } from '@/utils';

const investment = [
  {
    name: 'Maipo',
    data: [
      {
        branch: 'Maipu',
        resolution: 72,
        contracts: 85,
        contractValue: 2437000,
        totalGrams: 152,
        discountValue: 65000,
        type: 'gold',
        sales: 15000,
        grams: 100,
      },
      {
        branch: 'Plaza de Armas',
        resolution: 79,
        contracts: 192,
        contractValue: 442000,
        totalGrams: 440,
        discountValue: 125000,
        type: 'silver',
        sales: 22000,
        grams: 50,
      },
      {
        branch: 'Pumay',
        resolution: 81,
        contracts: 210,
        contractValue: 3700000,
        totalGrams: 320,
        discountValue: 95000,
        type: 'ingots',
        sales: 18500,
        grams: 80,
      },
    ],
    branchDetails: [
      {
        branch: 'Maipu',
        resolution: 72,
        contracts: 85,
        contractValue: 2437000,
        goldGrams: 120,
        showcaseGrams: 20,
        goldWatches: 5,
        ingots: 1,
        coins: 2,
        silverGrams: 50,
        exclusiveBrandUnits: 1,
      },
      {
        branch: 'Plaza de Armas',
        resolution: 79,
        contracts: 192,
        contractValue: 442000,
        goldGrams: 80,
        showcaseGrams: 15,
        goldWatches: 2,
        ingots: 0,
        coins: 1,
        silverGrams: 40,
        exclusiveBrandUnits: 2,
      },
      {
        branch: 'Pumay',
        resolution: 81,
        contracts: 210,
        contractValue: 3700000,
        goldGrams: 150,
        showcaseGrams: 30,
        goldWatches: 3,
        ingots: 2,
        coins: 3,
        silverGrams: 70,
        exclusiveBrandUnits: 1,
      },
    ],
  },
  {
    name: 'Pumay',
    data: [
      {
        branch: 'Pumay Centro',
        resolution: 77,
        contracts: 136,
        contractValue: 17175000,
        totalGrams: 1000,
        discountValue: 70000,
        type: 'ingots',
        sales: 10000,
        grams: 200,
      },
      {
        branch: 'Pumay Norte',
        resolution: 80,
        contracts: 120,
        contractValue: 9800000,
        totalGrams: 620,
        discountValue: 56000,
        type: 'gold',
        sales: 14000,
        grams: 150,
      },
      {
        branch: 'Pumay Sur',
        resolution: 85,
        contracts: 145,
        contractValue: 12050000,
        totalGrams: 800,
        discountValue: 61000,
        type: 'silver',
        sales: 17500,
        grams: 180,
      },
    ],
    branchDetails: [
      {
        branch: 'Pumay Centro',
        resolution: 77,
        contracts: 136,
        contractValue: 17175000,
        goldGrams: 500,
        showcaseGrams: 100,
        goldWatches: 3,
        ingots: 2,
        coins: 1,
        silverGrams: 300,
        exclusiveBrandUnits: 2,
      },
      {
        branch: 'Pumay Norte',
        resolution: 80,
        contracts: 120,
        contractValue: 9800000,
        goldGrams: 400,
        showcaseGrams: 70,
        goldWatches: 2,
        ingots: 1,
        coins: 2,
        silverGrams: 150,
        exclusiveBrandUnits: 1,
      },
      {
        branch: 'Pumay Sur',
        resolution: 85,
        contracts: 145,
        contractValue: 12050000,
        goldGrams: 450,
        showcaseGrams: 90,
        goldWatches: 4,
        ingots: 1,
        coins: 2,
        silverGrams: 200,
        exclusiveBrandUnits: 3,
      },
    ],
  },
];

const rows = [
  {
    attribute: 'Gramos Totales',
    gold: 3120,
    silver: 2200,
    showcasePicked: 600,
    ingots: 100,
    coins: 100,
    exclusiveBrand: 10,
  },
  {
    attribute: 'Valor Documentos',
    gold: 58000000,
    silver: 12500000,
    showcasePicked: 3500000,
    ingots: 125000,
    coins: 200000,
    exclusiveBrand: 500000,
  },
  {
    attribute: 'Promedio de compra (Costo)',
    gold: 3000,
    silver: 2000,
    showcasePicked: 4000,
    ingots: 8700,
    coins: 12500,
    exclusiveBrand: 3280,
  },
];

export const investmentColumns = [
  { id: 'branch', label: 'Sucursal' },
  { id: 'resolution', label: 'Nº Resolución' },
  { id: 'contracts', label: 'Nº Contratos' },
  { id: 'contractValue', label: 'Valor Contratos' },
  { id: 'totalGrams', label: 'Gramos Totales' },
  { id: 'discountValue', label: 'Valor Descuentos' },
];

export const branchDetailColumns = [
  { id: 'branch', label: 'Sucursal' },
  { id: 'resolution', label: 'N° Resolución' },
  { id: 'contracts', label: 'Número de Contratos' },
  { id: 'contractValue', label: 'Valor Resolución' },
  { id: 'goldGrams', label: 'Gramos de Oro (CR + CI)' },
  { id: 'showcaseGrams', label: 'Gramos de Oro Vitrina' },
  { id: 'goldWatches', label: 'Unidad Relojes Oro' },
  { id: 'ingots', label: 'Lingotes' },
  { id: 'coins', label: 'Monedas' },
  { id: 'silverGrams', label: 'Gramos Plata (AG)' },
  { id: 'exclusiveBrandUnits', label: 'Unidad Relojes Marca Exclusiva' },
];

const columns = [
  { id: 'attribute', label: 'Atributo' },
  { id: 'gold', label: 'Oro', field: formatCurrency },
  { id: 'silver', label: 'Plata', field: formatCurrency },
  { id: 'showcasePicked', label: 'Recogido en Vitrina', field: formatCurrency },
  { id: 'ingots', label: 'Lingotes', field: formatCurrency },
  { id: 'coins', label: 'Monedas', field: formatCurrency },
  { id: 'exclusiveBrand', label: 'Marca Exclusiva', field: formatCurrency },
];

export default {
  investment,
  rows,
  columns,
  investmentColumns,
  branchDetailColumns,
};
